services: 
  app: 
    build: .
    container_name: youdemi-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/youdemiapp
      - JWT_SECRET_KEY=dynasty_secret_key
      - NODE_ENV=development
      - PORT=5000

    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && node ./src/server.js"
  
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youdemiapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: